### ISSUE TITLE
"Enable playmode tests for all assemblies" option in docs does not exist

### ISSUE THREAD

**Issue by tomkail** [pubnub/unity#60]
On the [tutorial page](https://www.pubnub.com/docs/sdks/unity), the instruction to "Enable playmode tests for all assemblies." is not valid - this option doesn't exist on latest version of the Unity Test Framework. [This is a Unity issue](https://forum.unity.com/threads/enable-playmode-tests-for-all-assemblies-option-missing.1078463/), but they don't seem to want to fix it.
Can you suggest a workaround? It causes lots of errors to appear when installing the unitypackage, so it feels worth fixing! Can I suggest a version of the package without tests?

**Comment by blindgoat** [comment]
@tomkail Did you ever find a workaround?

Importing the PubNub Unity package into an EMPTY Unity 2021.3.8f1 (LTS) project gives 136 compiler errors. I'm assuming they'd be fixed if we could "enable playmode tests for all assemblies" but I don't see how.

**Comment by blindgoat** [comment]
Thanks, Tom :)

**Comment by MikeDobrzan** [comment]
Related to #61 – the issue should now be resolved. Thank you for your feedback.
