### ISSUE TITLE
GrantToken.cs does not belong in the PlayModeTests folder

### ISSUE THREAD

**Issue by tomkail** [pubnub/unity#61]
We deleted the PlayModeTests folder (it creates errors unless the Tests framework is set up in a particular way which no longer even seems to be supported by Unity) but doing so also deletes GrantToken.cs, which seems to be required for the plugin to compile.
We don't think this file is in the right place?

**Comment by Cj-Herman** [comment]
Just experience this issue as well, this should not be contained in a testing folder as it is responsible for core functionality, not testing only.

Could this be resolved in the next version?

**Comment by tomkail** [comment]
I've not had any luck reaching the devs through this page :( they seem to reply with fairly good advice if you go through the pubnub support channels, although they're not very keen to actually fix things.

**Comment by MikeDobrzan** [comment]
The PlayModeTests issue has been resolved – we are no longer providing those by default. Also, the documentation now reflects the change.

Those tests were just introducing confusion, and – if they're needed for whatever reason, they're still available in the repository.
