### ISSUE TITLE
A basic demo scene?

### ISSUE THREAD

**Issue by tomkail** [pubnub/unity#63]
The demo scene that comes with the package is super powerful, but we'd have found a basic text chat (send + recieve messages) demo to be really useful! Any chance of that?

**Comment by MikeDobrzan** [comment]
There is an ExampleScene in the package. It is very basic, but it covers the whole SDK.

We will be working on a "real use case" examples in the next iteration of the SDK, so stay tuned!

Resolving this for now, I will make sure you're notified when we have the more advanced demo scene ready.
