### ISSUE TITLE
Better error logging when requests fail

### ISSUE THREAD

**Issue by tomkail** [pubnub/unity#78]
Something in my code has been causing PubNubAPI.BuildRequests.EncodeURL to hit a null ref error. 
However, it's almost impossible to tell what, because the QueueManager means that the error log goes as far as the Update loop for QueueManager and no further.
What's the expected flow for debugging in this case?

**Comment by MikeDobrzan** [comment]
Added a log that should help in debugging those kind of errors in the future. Thanks for the feedback!
