### ISSUE TITLE
PubNub's try catch statements prevent Unity logging null ref exceptions in callbacks

### ISSUE THREAD

**Issue by tomkail** [pubnub/unity#79]
We're expected to use callbacks when using PubNub to trigger game-side code, but doing so means we can't see errors.
This is INCREDIBLY annoying, since it makes detecting game-side errors really difficult.
We've hacked around this by throwing our own logs at the time that PubNub eats them in a try catch, but this really needs a real solution ASAP.

**Comment by MikeDobrzan** [comment]
The new release logs the exception errors by default, and if that proves to be not enough, there's a new flag: `ENABLE_PUBNUB_EXCEPTIONS` - it will throw within the callback. Thanks for your feedback!
